#+TITLE: Script untuk Compiling Kernel dan Pack Boot.img
#+AUTHOR: Christian Alexander
#+EMAIL: alexforsale@yahoo.com
#+LANGUAGE: id

Scripts ini adalah bagian dari tutorial di http://mak2006.blogspot.co.id/2017/06/compile-kernel-android.html. Check ke link tersebut untuk informasi lebih detail mengenai fungsi - fungsi didalam script tersebut.

Clone repository ini atau download [[https://github.com/alexforsale/kernel-test-script/releases][tarball-nya]], ubah nama file variables.txt.contoh menjadi variables.txt, edit isi variable-nya sesuaikan dengan lokasi dan nama yang diinginkan. Lalu jalankan script-nya.

Ada dua script didalam repository ini
* [[file:kernel.sh][kernel.sh]]
Script ini berfungsi untuk compiling kernel.
** Contoh Penggunaan
#+begin_src shell
./kernel.sh all
#+end_src
Akan melakukan compiling semua function. Untuk function lainnya:
 - Zimage: untuk compile zImage
 - dtbs: untuk compile dts
 - modules: untuk compile modules
 - clean: make mrproper
 - savedefconfig: menyimpan file .config ke source kernel
* [[file:pack.sh][pack.sh]] 
Script ini berfungsi untuk packing boot.img
** Contoh Penggunaan
#+begin_src shell
./pack.sh all
#+end_src
Akan melakukan packing semua function. Untuk function lainnya:
 - dtb: untuk pack dt.img
 - ramdisk: untuk pack ramdisk.img
 - boot. untuk pack boot.img

* [[file:variables.txt.contoh][variables.txt.contoh]]
File ini merupakan contoh dari file variable.txt, ubah dan sesuaikan isinya lalu /rename/ file ini menjadi variable.txt. isi dari file ini yang akan di source oleh kedua script diatas.

Jika tidak melakukan modifikasi pada ramdisk (seperti editing file init.rc, atau mengganti binary init dan lainnya), ambil ramdisk dari boot.img lain yang ingin dipakai, letakkan di /directory/ ini dengan nama ramdisk.img.
* Binary Tambahan: Unpackbootimg
Binary ini juga didapat dari hasil compile ROM LineageOS 12.1, cara penggunaan:
#+begin_src shell
bin/unpackbootimg -i <path-ke-boot.img>
#+end_src
Setiap parameter boot akan dibuat menjadi satu file teks dengan nama yang sama dengan parameter-nya, seperti boot.img-base, boot.img-cmdline, boot.img-pagesize, boot.img-ramdisk_offset dan lainnya, isi dari file - file ini yang perlu dimasukkan kedalam variable.txt
